# This file was generated by GoReleaser. DO NOT EDIT.
cask "tflat" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "7309bb9741bab0e7e12e3cfa718ebbe3f0a4ea9b85eb6ae46b19b48312cf40e3"
      url "https://github.com/winebarrel/tflat/releases/download/v#{version}/tflat_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5777c1112675769e138184fdb8f51b87028601d8459ed157bf0a0bb16ce9e9a4"
      url "https://github.com/winebarrel/tflat/releases/download/v#{version}/tflat_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3abe97085d12e2756aa457f2dee28a45438d964fbc6233c42e96a5ebbfb1a16c"
      url "https://github.com/winebarrel/tflat/releases/download/v#{version}/tflat_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4f740c23e5083dfa2b80a3f8fcdf37a67b201d52e0bb1b1ad4eb9286a46ada24"
      url "https://github.com/winebarrel/tflat/releases/download/v#{version}/tflat_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tflat"
  desc "Flatten Terraform modules into the parent with moved blocks for state migration."
  homepage "https://github.com/winebarrel/tflat"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tflat"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tflat"]
    end
  end

  # No zap stanza required

end
