# This file was generated by GoReleaser. DO NOT EDIT.
cask "tflat" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "73c6c936c147c8c43e3812969c5271f00c05a514e6f09a0045e911e96b25247e"
      url "https://github.com/winebarrel/tflat/releases/download/v#{version}/tflat_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cca247323f43b16a9bd49f4bf23e170ec621712edf8215e380ca3f00fb4c90ab"
      url "https://github.com/winebarrel/tflat/releases/download/v#{version}/tflat_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "913fbb9600f9d18f4e715cb22d42a07a4b940769ab5c50e4e8289c2f69451ba5"
      url "https://github.com/winebarrel/tflat/releases/download/v#{version}/tflat_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b8d27f85990e014b44328ccb09b26bee3c64bcaebf078bed9b37618a9e940c04"
      url "https://github.com/winebarrel/tflat/releases/download/v#{version}/tflat_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tflat"
  desc "Flatten Terraform modules into the parent with moved blocks for state migration."
  homepage "https://github.com/winebarrel/tflat"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tflat"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tflat"]
    end
  end

  # No zap stanza required

end
