# This file was generated by GoReleaser. DO NOT EDIT.
cask "tflat" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "e8f7d6482b8432d2f16af9e5adcbbfa581edcca5364c96327b718f846d62a573"
      url "https://github.com/winebarrel/tflat/releases/download/v#{version}/tflat_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "47fc92f74506dc47cf0970574dab5c09d28740c086e64cc53ef18c39c6543985"
      url "https://github.com/winebarrel/tflat/releases/download/v#{version}/tflat_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a8d34a80601e0133610badd55a4159be8207df04eaabc28ecdc7c3554837b22e"
      url "https://github.com/winebarrel/tflat/releases/download/v#{version}/tflat_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "43032766bce7a6e7d5f968438583a906f8f14bc5919b6c11df41e640311cc94b"
      url "https://github.com/winebarrel/tflat/releases/download/v#{version}/tflat_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tflat"
  desc "Flatten Terraform modules into the parent with moved blocks for state migration."
  homepage "https://github.com/winebarrel/tflat"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tflat"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tflat"]
    end
  end

  # No zap stanza required

end
